version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfile/server.Dockerfile
    environment:
      SERVER_LOG_LEVEL: '0'
      SERVER_LOG_JSON: 'false'
      SERVER_ADDRESS: ':8080'
      SERVER_SHUTDOWN_TIMEOUT: '1000'
      SERVER_CONNECTION_TIMEOUT: '2000'  
      HASHCASH_BITS: '5'
      HASHCASH_TTL: '2000'
    ports:
      - 8080:8080  

  client:
    container_name: client
    build:
      context: .
      dockerfile: dockerfile/client.Dockerfile
    environment:
      CLIENT_LOG_LEVEL: '0'
      CLIENT_LOG_JSON: 'false'
      CLIENT_SERVER_ADDRESS: 'server:8080'
      HASHCASH_COMPUTE_MAX_ATTEMPTS: '1000000'
    depends_on:
      - server       